In [1]:
# pandas is pandas provides data structures and tools to read, clean, analyze, and manipulate data easily
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.23.2 in /Users/ramrekhayadav/.pyenv/versions/3.11.9/lib/python3.11/site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ramrekhayadav/.pyenv/versions/3.11.9/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/ramrekhayadav/.pyenv/versions/3.11.9/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 4.5 MB/s eta 0:00:0000:0100:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.5/348.5 kB 5.0 MB/s eta 0:00:00a 0:00:01
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.3.3 pytz-2025.2 tzdata-2025.3

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [1]:
import pandas as pd
#Series is one-dimensional array like object, it is similar to column in a table

data=[1,2,3,4,5]
sereis=pd.Series(data)
print(sereis)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
index=['a','b','c','d','e']
sereis=pd.Series(data,index=index)
print(sereis)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
data1={'a':1,'b':2,'c':3}
series_dict=pd.Series(data1)
print(series_dict)
#key consider as indes and values as series

a    1
b    2
c    3
dtype: int64

In [7]:
#dataframe a DataFrame is a two-dimensional, size-mutable, and heterogeneous data structure with labeled axes (rows and columns). It is similar to a table in a relational database or an Excel spreadsheet.

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [14]:
df.loc[0:1] # it will print first row with index

    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles

In [15]:
df.iloc[0:1]

    Name  Age      City
0  Alice   25  New York

In [16]:
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [18]:
a=df.at[1,'Age']
print(a)

30

In [19]:
print(df.iat[2,2])

Chicago

In [20]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [33]:
# adding a column
df["Salary"]=[5000,60000,70000]
df

      Name  Age         City  Salary
0    Alice   25     New York    5000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [34]:
#remove a column why axis by default it will search vai column index,like 0,1,2 but if axis is 1 it will look like name,age so

df.drop("Salary", axis=1)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [35]:
df

      Name  Age         City  Salary
0    Alice   25     New York    5000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [37]:
df.drop("Salary",axis=1,inplace=True)

In [38]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago